config/routes.rb
Rails.application.routes.draw do
  get 'subjects/index'

  get 'subjects/show'

  get 'subjects/create'

  get 'subjects/delete'

  get 'subjects/destroy'

  get 'subjects/edit'

  get 'subjects/update'

  get 'subjects/new'

  resources :questions
  resources :users
  resources :problems
  resources :assignments
  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'mechanics' => 'static_pages#mechanics'
  get 'emag' => 'static_pages#emag'
  get 'ap1' => 'static_pages#ap1'
  get 'ping_pong' => 'static_pages#ping_pong'
  get 'sci_oly' => 'static_pages#sci_oly'
  get 'signup' => 'users#new'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  has_many :questions
  has_many :problems, through: :questions
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :subject
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  has_many :questions
  has_many :problem_parts
  has_many :assignments, through: :questions

  accepts_nested_attributes_for :problem_parts, allow_destroy: true,
    reject_if: lambda {|attributes| attributes['answer'].blank? || attributes['statement'].blank?}
end

app/models/problem_part.rb
class ProblemPart < ActiveRecord::Base
  belongs_to :problem
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :problem
  belongs_to :assignment
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX =/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :common_content, :except => :destroy
  before_action :find_assignment, :only => [:show, :update, :edit, :destory]

  def new
    @assignment = Assignment.new
  end

  def index
    @assignments = Assignment.order(:created_at)
  end

  def create
    @assignment = Assignemnt.new(assignment_params)
    #add each submitted problem to the assignment
    problem_list.each do |prob|
      @assignment.problems << prob
    end

    if @assignment.save
      flash[:success] = "Assignment created successfully"
      redirect_to @assignment
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  private

    def assignment_params
      params.require(:assignment).permit(:name)
    end

    def find_assignment
      @assignment = Assignment.find(params[:id])
    end

    def problem_list
      params.require(:problems)
    end

    def common_content
      @page = "main"
    end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :common_content, :except => :destroy
  before_action :find_problem, :only => [:show, :edit, :update, :destroy]
  def index
    @problems = Problem.all
  end

  def show
  end

  def new
    @problem = Problem.new
  end

  def edit
    
  end

  def create
    @problem = Problem.new(problem_params)
    if @problem.save
      flash[:success] = "Problem created successfully."
      redirect_to @problem
    else
      render 'new'
    end
  end

  def update
    if @problem.update(problem_params)
      flash[:success] = "Problem updated"
      redirect_to @problem
    else
      render :edit
    end
  end


  def destroy
  end

  private
    def problem_params
      params.require(:problem).permit(:topic, :problem_text,:id,
                                     problem_parts_attributes: [:statement,:answer,:id,:_destroy])
    end

    def find_problem
      @problem = Problem.find(params[:id])
      @parts = @problem.problem_parts
    end

    def common_content
      @page = "main"
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:problem_id, :assignment_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  attr_reader :page
  def home
    @page = 'main'
    @title = "MCDUFF PHYSICS"
  end

  def contact
    @page = 'contact'
    @title = @page.upcase
  end

  def ap1
    @page = 'ap1'
    @title = @page.upcase
  end

  def mechanics
    @page = 'mechanics'
    @title = @page.upcase
  end

  def emag
    @page = 'emag'
    @title = @page.upcase
  end

  def ping_pong
    @page = 'main'
    @title = "PING PONG"
  end

  def sci_oly
    @page = 'main'
    @title = "SCI OLY"
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :find_subject, :only => [:show, :update, :destroy, :edit]
  def index
    @subjects = Subject.all
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      flash[:success] = "Subject created successfully"
      redirect_to @subject
    else
      render 'new'
    end
  end

  def destroy
    @subject = Subject.find(params[:id])
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :common_content, :except => [:delete, :destroy]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to McDuff Physics!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  private

  def common_content
    @page = "main"
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  #Returns the Gravatar for the given user
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt:user.name, class: "gravatar")
  end
end

app/views/assignments/create.html.erb
<h1>Assignments#create</h1>
<p>Find me in app/views/assignments/create.html.erb</p>

app/views/assignments/destroy.html.erb
<h1>Assignments#destroy</h1>
<p>Find me in app/views/assignments/destroy.html.erb</p>

app/views/assignments/edit.html.erb
<h1>Assignments#edit</h1>
<p>Find me in app/views/assignments/edit.html.erb</p>

app/views/assignments/index.html.erb
<h1>Assignments#index</h1>
<p>Find me in app/views/assignments/index.html.erb</p>

app/views/assignments/new.html.erb
<h1>Create Assignment</h1>

<%= form_for @assignment do |f| %>
  <%= f.label :hw_id %>
  <%= f.text_field :hw_id, class: 'form-control' %>


  <%= f.label :hw_id %>
  <%= f.text_field :hw_id, class: 'form-control' %>

  <%= f.label :hw_id %>
  <%= f.text_field :hw_id, class: 'form-control' %>

  <%= f.label :hw_id %>
  <%= f.text_field :hw_id, class: 'form-control' %>

  <%= f.label :hw_id %>
  <%= f.text_field :hw_id, class: 'form-control' %>

  <%= f.label :hw_id %>
  <%= f.text_field :hw_id, class: 'form-control' %>

app/views/assignments/show.html.erb
<h1>Assignments#show</h1>
<p>Find me in app/views/assignments/show.html.erb</p>

app/views/assignments/update.html.erb
<h1>Assignments#update</h1>
<p>Find me in app/views/assignments/update.html.erb</p>

app/views/problems/_form.html.erb
<%= form_for @problem do |f| %>
  <%= f.label :topic %>
  <%= f.text_field :topic %>

  <%= f.label :problem_text %>
  <%= f.text_area :problem_text %>

  <%= f.nested_fields_for :problem_parts do |ff| %>
    <%= ff.label 'Question Part' %>
    <%= ff.text_area :statement %>

    <%= ff.label 'Answer' %>
    <%= ff.text_field :answer %>
    <%= ff.remove_nested_fields_link %>
  <% end %>
  <%= f.add_nested_fields_link :problem_parts %>
  <%= f.submit %>
<% end %>

app/views/problems/create.html.erb
<h1>Problems#create</h1>
<p>Find me in app/views/problems/create.html.erb</p>

app/views/problems/delete.html.erb
<h1>Problems#delete</h1>
<p>Find me in app/views/problems/delete.html.erb</p>

app/views/problems/destroy.html.erb
<h1>Problems#destroy</h1>
<p>Find me in app/views/problems/destroy.html.erb</p>

app/views/problems/edit.html.erb
<h1>Edit Problem</h1>

<%= render 'form' %>

<%= link_to 'Problems', problems_path %>
<%= link_to 'Back to problem', @problem %>

app/views/problems/index.html.erb
<h1>Problems</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Problem Text</th>
    <th>Topic</th>
  </tr>
  <% @problems.each do |problem| %>
    <tr>
      <td><%= link_to problem.id, problem %></td>
      <td><%= problem.problem_text %></td>
      <td><%= problem.topic %></td>
      <td><%= link_to 'edit', edit_problem_path(problem) %>
    </tr>
  <% end %>
</table>
<%= link_to "Create new Problem", new_problem_path, class: "btn btn-primary" %>

app/views/problems/new.html.erb
<h1>New Problem</h1>
<%= render 'form' %>
<%= link_to 'Problems', problems_path %>

app/views/problems/show.html.erb
<h1><%= @problem.id %></h1>

<h2><%= @problem.topic %></h2>
<p><%= @problem.problem_text %><p>
<% @parts.each do |part| %>
  <p><%= part.statement %></p>
  <p><%= part.answer %></p>
<% end %>

<%= link_to "Back", problems_path %>
<%= link_to "edit", edit_problem_path(@problem) %>

app/views/problems/update.html.erb
<h1>Problems#update</h1>
<p>Find me in app/views/problems/update.html.erb</p>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :problem_id %><br>
    <%= f.text_field :problem_id %>
  </div>
  <div class="field">
    <%= f.label :assignment_id %><br>
    <%= f.text_field :assignment_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Problem</th>
      <th>Assignment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.problem %></td>
        <td><%= question.assignment %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Problem:</strong>
  <%= @question.problem %>
</p>

<p>
  <strong>Assignment:</strong>
  <%= @question.assignment %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1>Physics happens here!</h1>
  <p>
  This is where you'll find homework problems and
  video lessons.
  </p>
  <p>
  <%= link_to "Sign Up", signup_path %> now if you haven't already
  </p>
</div>

<div class="subject-panes">
  <h2>Classes and Clubs</h2>
  <p>
  Head on over to the class or club that you're
  looking for.
  </p>
  <div class="row">
    <div class="col-md-4">
      <div class="thumbnail">
        <%= link_to(image_tag("plasma_lamp.jpg"), ap1_path) %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="thumbnail">
        <%= link_to(image_tag("ferro_fluid.jpg"), emag_path ) %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="thumbnail">
        <%= link_to(image_tag("Trebuchet.jpg"),mechanics_path) %>
      </div>
    </div>
  </div>
  <div class="row">

    <div class="col-md-4 col-md-offset-2">
      <div class="thumbnail">
        <%= link_to(image_tag("table_tennis.jpg"), ping_pong_path) %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="thumbnail">
        <%= link_to(image_tag("tesla.jpg"), sci_oly_path) %>
      </div>
    </div>

  </div>

</div>

app/views/static_pages/mechanics.html.erb
<div class="container">
  <h1 class="boom">MECHANICS</h1>
  <p>
  Welcome to the Mechanics page. Currently it's not the prettiest thing in the
  world, but it'll get updated along the way. I'm aiming for functional right now.
  </p>
  <p>
  The first thing you'll probably want is a copy of the syllabus; luckily all you have
  to do is click <a href="/res/downloads/apcmsyllabus.pdf">here</a>.
  </p>
  <ul>
    <li>
    <p>
    Here is the key for the <a href="revKey.jpg">Test 1 review</a>

    </p>

    </li>
    <li>
    <p>
    Here is the key for the <a href="FBDpractice.pdf">FBD and Newton's Laws practice</a>
    </p>
    </li>
    <li>
    <p>
    Test review <a href="test2pracSolutions.pdf">solutions</a> for thursday problems
    </p>
    </li>
    <li>
    <p>
    Here's the <a href="https://wikispaces.com/join/F4XN7NF">link to join the wiki </a> we'll be building to review
    </p>
    <p>
    Once you've joined the wiki you can get there using  <a href="https://mcduff-physics.wikispaces.com/">this link</a>
    </p>
    </li>
  </ul>

</div>

app/views/subjects/create.html.erb
<h1>Subjects#create</h1>
<p>Find me in app/views/subjects/create.html.erb</p>

app/views/subjects/delete.html.erb
<h1>Subjects#delete</h1>
<p>Find me in app/views/subjects/delete.html.erb</p>

app/views/subjects/destroy.html.erb
<h1>Subjects#destroy</h1>
<p>Find me in app/views/subjects/destroy.html.erb</p>

app/views/subjects/edit.html.erb
<h1>Subjects#edit</h1>
<p>Find me in app/views/subjects/edit.html.erb</p>

app/views/subjects/index.html.erb
<h1>Subjects#index</h1>
<p>Find me in app/views/subjects/index.html.erb</p>

app/views/subjects/new.html.erb
<h1>Subjects#new</h1>
<p>Find me in app/views/subjects/new.html.erb</p>

app/views/subjects/show.html.erb
<h1>Subjects#show</h1>
<p>Find me in app/views/subjects/show.html.erb</p>

app/views/subjects/update.html.erb
<h1>Subjects#update</h1>
<p>Find me in app/views/subjects/update.html.erb</p>

app/views/users/index.html.erb
<div class="container">
  <h1>Users</h1>
  <table>
    <tr>
      <th class="user_col">Name</th>
      <th class="email_col">Email</th>
    </tr>
  <% @users.each do |user| %>
    <tr>
      <td class="user_col">
        <%= link_to user.name, user %>
      </td>
      <td class="email_col">
        <%= user.email %>
      </td>
    </tr>
  <% end %>
</table>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign up</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password,  class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control'%>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container" >
  <% provide(:title, @user.name) %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1>
          <%= gravatar_for @user %>
          <%= @user.name %>
        </h1>
      </section>
    </aside>
  </div>
</div>