config/routes.rb
Rails.application.routes.draw do
  get 'subjects/index'

  get 'subjects/show'

  get 'subjects/create'

  get 'subjects/delete'

  get 'subjects/destroy'

  get 'subjects/edit'

  get 'subjects/update'

  get 'subjects/new'

  resources :questions
  resources :users
  resources :problems
  resources :assignments
  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'mechanics' => 'static_pages#mechanics'
  get 'emag' => 'static_pages#emag'
  get 'ap1' => 'static_pages#ap1'
  get 'ping_pong' => 'static_pages#ping_pong'
  get 'sci_oly' => 'static_pages#sci_oly'
  get 'signup' => 'users#new'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  has_many :questions
  has_many :problems, through: :questions
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :subject
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  has_many :questions
  has_many :problem_parts
  has_many :assignments, through: :questions

  accepts_nested_attributes_for :problem_parts, allow_destroy: true,
    reject_if: lambda {|attributes| attributes['answer'].blank? || attributes['statement'].blank?}
end

app/models/problem_part.rb
class ProblemPart < ActiveRecord::Base
  belongs_to :problem
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :problem
  belongs_to :assignment
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX =/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :common_content, :except => :destroy
  before_action :find_assignment, :only => [:show, :update, :edit, :destory]

  def new
    @assignment = Assignment.new
  end

  def index
    @assignments = Assignment.order(:created_at)
  end

  def create
    @assignment = Assignemnt.new(assignment_params)
    #add each submitted problem to the assignment
    problem_list.each do |prob|
      @assignment.problems << prob
    end

    if @assignment.save
      flash[:success] = "Assignment created successfully"
      redirect_to @assignment
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  private

    def assignment_params
      params.require(:assignment).permit(:name)
    end

    def find_assignment
      @assignment = Assignment.find(params[:id])
    end

    def problem_list
      params.require(:problems)
    end

    def common_content
      @page = "main"
    end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :common_content, :except => :destroy
  before_action :find_problem, :only => [:show, :edit, :update, :destroy]
  def index
    @problems = Problem.all
  end

  def show
  end

  def new
    @problem = Problem.new
  end

  def edit
    
  end

  def create
    @problem = Problem.new(problem_params)
    if @problem.save
      flash[:success] = "Problem created successfully."
      redirect_to @problem
    else
      render 'new'
    end
  end

  def update
    if @problem.update(problem_params)
      flash[:success] = "Problem updated"
      redirect_to @problem
    else
      render :edit
    end
  end


  def destroy
  end

  private
    def problem_params
      params.require(:problem).permit(:topic, :problem_text,:id,
                                     problem_parts_attributes: [:statement,:answer,:id,:_destroy])
    end

    def find_problem
      @problem = Problem.find(params[:id])
      @parts = @problem.problem_parts
    end

    def common_content
      @page = "main"
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:problem_id, :assignment_id)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :find_subject, :only => [:show, :update, :destroy, :edit]
  def index
    @subjects = Subject.all
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      flash[:success] = "Subject created successfully"
      redirect_to @subject
    else
      render 'new'
    end
  end

  def destroy
    @subject = Subject.find(params[:id])
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :common_content, :except => [:delete, :destroy]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to McDuff Physics!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  private

  def common_content
    @page = "main"
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  #Returns the Gravatar for the given user
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt:user.name, class: "gravatar")
  end
end

app/views/layouts/_ap1_header.html.erb
<header class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <a class="navbar-brand" href="/">MCDUFF PHYSICS</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
        <%= link_to "AP1", ap1_path %>
        </li>
        <li>
        <%= link_to "LABS", "#"%>
        </li>
        <li class="dropdown">
        <%= link_to "TOPICS", "#", {class: "dropdown-toggle", "data-toggle" => "dropdown"} %>
        <ul class="dropdown-menu">
          <li>
          <%= link_to "Motion Along a Straight Line", "#" %>
          </li>
          <li>
          <%= link_to "Vectors", "#" %>
          </li>
          <li>
          <%= link_to "Motion in Two and Three Dimensions", "#" %>
          </li>
          <li>
          <%= link_to "Force and Motion 1", "#" %>
          </li>
          <li>
          <%= link_to "Force and Motion 2", "#" %>
          </li>
          <li>
          <%= link_to "Kinetic Energy and WOrk", "#" %>
          </li>
          <li>
          <%= link_to "Potential Energy and Conservation", "#" %>
          </li>
          <li>
          <%= link_to "Center of Mass and Linear Momentum", "#" %>
          </li>
          <li>
          <%= link_to "Rotation", "#" %>
          </li>
          <li>
          <%= link_to "Rolling, Torque, and Angular Momentum", "#" %>
          </li>
          <li>
          <%= link_to "Equilibrium and Elasticity", "#" %>
          </li>
          <li>
          <%= link_to "Gravitation", "#" %>
          </li>
          <li>
          <%= link_to "Oscillations", "#" %>
          </li>
        </ul>
        </li>
        <li>
        <%= link_to "HOMEWORK", "#" %>
        </li>
        <li>
        <%= link_to "CALENDAR", "#" %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
        <%= link_to "RESOURCES", "#" %>
        <li>
        <%= link_to "CONTACT", "#" %>
        </li>
      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
</header>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul class="nav nav-pills">
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div id="logo"><%= link_to 'MCDUFF PHYSICS', root_path %></div>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li>
          <%= link_to 'PHYSICS 1', ap1_path %>
          </li>
          <li>
          <%= link_to 'MECHANICS', mechanics_path%>
          </li>
          <li>
          <%= link_to 'E&M', emag_path%>
          </li>
          <li>
          <%= link_to 'PING PONG', ping_pong_path%>
          </li>
          <li>
          <%= link_to 'SCI OLY', sci_oly_path%>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
          <%= link_to 'RIVER RIDGE',"http://www.cherokee.k12.ga.us/Schools/riverridge-hs/default.aspx" %>
          </li>
          <li>
          <%= link_to 'CONTACT', contact_path %>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>

  </header>

app/views/layouts/_main_header.html.erb
<header class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div id="logo"><%= link_to 'MCDUFF PHYSICS', root_path, class: "navbar-brand" %></div>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li>
          <%= link_to 'PHYSICS 1', ap1_path %>
          </li>
          <li>
          <%= link_to 'MECHANICS', mechanics_path%>
          </li>
          <li>
          <%= link_to 'E&M', emag_path%>
          </li>
          <li>
          <%= link_to 'PING PONG', ping_pong_path%>
          </li>
          <li>
          <%= link_to 'SCI OLY', sci_oly_path%>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
          <%= link_to 'RIVER RIDGE',"http://www.cherokee.k12.ga.us/Schools/riverridge-hs/default.aspx" %>
          </li>
          <li>
          <%= link_to 'CONTACT', contact_path %>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
</header>

app/views/layouts/_mechanics_header.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">MCDUFF PHYSICS</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "HOME", mechanics_path %></li>
        <li><a href="/phpBB3/viewforum.php?f=4">LABS</a></li>
        <li class="dropdown">
        <%= link_to "TOPICS", "#", {class: "dropdown-toggle", "data-toggle" => "dropdown"} %>
        <ul class="dropdown-menu">
          <li>
          <%= link_to "Motion Along a Straight Line", "#" %>
          </li>
          <li>
          <%= link_to "Vectors", "#" %>
          </li>
          <li>
          <%= link_to "Motion in Two and Three Dimensions", "#" %>
          </li>
          <li>
          <%= link_to "Force and Motion 1", "#" %>
          </li>
          <li>
          <%= link_to "Force and Motion 2", "#" %>
          </li>
          <li>
          <%= link_to "Kinetic Energy and Work", "#" %>
          </li>
          <li>
          <%= link_to "Potential Energy and Conservation", "#" %>
          </li>
          <li>
          <%= link_to "Center of Mass and Linear Momentum", "#" %>
          </li>
          <li>
          <%= link_to "Rotation", "#" %>
          </li>
          <li>
          <%= link_to "Rolling, Torque, and Angular Momentum", "#" %>
          </li>
          <li>
          <%= link_to "Equilibrium and Elasticity", "#" %>
          </li>
          <li>
          <%= link_to "Gravitation", "#" %>
          </li>
          <li>
          <%= link_to "Oscillations", "#" %>
          </li>
        </ul>
        </li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">HOMEWORK <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><a href="/apcm/HW/hw1.php">HW1</a></li>
          <li><a href="/apcm/HW/hw2.php">HW2</a></li>
          <li><a href="/apcm/HW/cm3.php">HW3</a></li>
          <li><a href="/apcm/HW/cm4.php">HW4</a></li>
          <li><a href="/apcm/HW/cm5.php">HW5</a></li>
          <li><a href="/apcm/HW/cm6.php">HW6</a></li>
          <li><a href="/apcm/HW/cm7.php">HW7</a></li>
          <li><a href="/apcm/HW/cm8.php">HW8</a></li>
          <li><a href="/apcm/HW/cm9.php">HW9</a></li>
          <li><a href="/apcm/HW/cm10.php">HW10</a></li>
          <li><a href="/apcm/HW/cm11.php">HW11</a></li>
          <li><a href="/apcm/HW/cm12.php">HW12</a></li>
        </ul>
        </li>
        <li><%= link_to "CALENDAR", "#" %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "RESOURCES", "#" %></li>
        <li><%= link_to "CONTACT", "#" %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= @title %></title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/#{@page}_header" %>
<div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>


  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>